# Generated by Django 4.0.1 on 2022-01-26 12:53

from django.db import migrations, models
import route.models
import route.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actual', models.ImageField(storage=route.storage.OverwriteStorage(), upload_to=route.models.actual_path)),
                ('Expected', models.ImageField(storage=route.storage.OverwriteStorage(), upload_to=route.models.expected_path)),
            ],
        ),
    ]
